globals = {
    "CreateFrame",
    "UIParent",
    "GetMoney",
    "GetCoinTextureString",
    "SlashCmdList",
    "SLASH_GOLDTRACKER1",
    "GoldTrackerDB",
    "GoldTrackerHistory",
    "date",
    "print",
    "math",
    "string",
    "table",
    "time",
}